# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170625_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='file',
        ),
    ]
